# Copyright (C) 2020-2022 R

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for AutoUpdate Script
LUCI_DEPENDS:=+wget
LUCI_PKGARCH:=all
PKG_VERSION:=1
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
